# Server Port
server.port=8080

# Oracle XE Database Connection Settings
# Dikkat: Ba?lant? adresi :XE yerine /XEPDB1 (Pluggable Database) olarak güncellendi
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=customer_db
spring.datasource.password=customer_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Swagger UI Path
springdoc.swagger-ui.path=/swagger-ui.html